name: Android Debug (AGP7/Gradle7.6.1/Java11)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZIP_NAME: SalesMasterApp.zip
      PROJECT_DIR: project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Verify and unzip the project ZIP ----
      - name: Verify ZIP exists
        run: |
          ls -la
          [ -f "$ZIP_NAME" ] || { echo "ZIP '$ZIP_NAME' not found at repo root"; exit 1; }

      - name: Unzip project
        run: |
          rm -rf "$PROJECT_DIR"
          mkdir -p "$
