name: Android Debug Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZIP_NAME: SalesMasterApp.zip
      PROJECT_DIR: project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify ZIP exists
        run: |
          ls -la
          if [ ! -f "$ZIP_NAME" ]; then
            echo "ERROR: $ZIP_NAME not found at repo root"
            exit 1
          fi

      - name: Unzip project
        run: |
          rm -rf $PROJECT_DIR
          mkdir -p $PROJECT_DIR
          unzip -q $ZIP_NAME -d $PROJECT_DIR
          echo "Contents after unzip:"
          find $PROJECT_DIR -maxdepth 3 -type f -print

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Locate Gradle wrapper
        id: locate
        run: |
          WRAPPER_PATH=$(find $PROJECT_DIR -maxdepth 3 -type f -name gradlew -print -quit)
          if [ -z "$WRAPPER_PATH" ]; then
            echo "No gradlew found in project" >&2
            exit 1
          fi
          echo "wrapper=$WRAPPER_PATH" >> $GITHUB_OUTPUT
          echo "dir=$(dirname $WRAPPER_PATH)" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x ${{ steps.locate.outputs.wrapper }}

      - name: Build Debug APK
        working-directory: ${{ steps.locate.outputs.dir }}
        run: ${{ steps.locate.outputs.wrapper }} --no-daemon --stacktrace assembleDebug

      - name: Upload Debug APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            ${{ steps.locate.outputs.dir }}/**/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
